image: gcc

before_script:
  - make
  - cd tests

test_cc:
  script: ./run_all.sh cc cc
  stage: test

test_clang:
  script:
    - apt-get install -y "^clang-[0-9]+(\\.[0-9]+)*$"
    - ./run_all.sh clang clang++
  stage: test

test_gcc:
  script: ./run_all.sh gcc g++
  stage: test