image: gcc

test_cc:
  script:
    - cd tests
    - ./run_all.sh cc cc
  stage: test

test_clang:
  script:
    - cd tests
    - ./run_all.sh clang clang++
  stage: test

test_gcc:
  script:
    - cd tests
    - ./run_all.sh gcc g++
  stage: test