#---------------------------------#
#      general configuration      #
#---------------------------------#
version: 1.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  # only:
  #   - master
  # blacklist
  except:
    - gh-pages



#---------------------------------#
#    environment configuration    #
#---------------------------------#
# Build worker image (VM template)
image: Visual Studio 2017

# clone directory
clone_folder: c:\projects\lassert

# fetch repository as zip archive
shallow_clone: true



#---------------------------------#
#       build configuration       #
#---------------------------------#
platform:
 - x86
 - x64
 
 

#---------------------------------#
#       tests configuration       #
#---------------------------------#
before_test:
 - cd tests\c\classert
 - if exist debug (cd debug) else (cd x64\debug)

test_script:
 - CLAssert.exe -nt > out.txt || type out.txt
 - echo N | comp /a out.txt c:\projects\lassert\tests\win_ref.txt